[pytest]
testpaths = tests

python_files = test_*.py
python_classes = Test*
python_functions = test_*

addopts = -ra --strict-markers

markers =
    smoke: critical checks for basic functionality
    regression: full checks of the application
    api: API test cases
